import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  creator: "Jiackey",
  authors: [{ name: "Jiackey" }],
};

import { ParticlesBackground } from "@/components/ui/ParticlesBackground";
import { ThemeMetrics } from "@/components/ui/ThemeMetrics";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-registry="jiackey-build-primary">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        id="jiackey-app-root"
      >
        <ThemeMetrics />
        <ParticlesBackground />
        {children}
      </body>
    </html>
  );
}
